---
- name: Create a sandbox instance
  hosts: localhost
  gather_facts: False
  vars:
    keypair: mykey3
    instance_type: t2.micro
    security_group: EC2SecurityGroup1
    image: ami-07ebfd5b3428b6f4d
    region: us-east-1
  tasks:
    - name: Launch instance
      ec2:
         key_name: "{{ keypair }}"
         group: "{{ security_group }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         region: "{{ region }}"
         vpc_subnet_id: subnet-f49f73d5
         assign_public_ip: yes
      register: ec2

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: launched
      loop: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      delegate_to: "{{ item.public_dns_name }}"
      key_name: "{{ keypair }}"
      remote_user: ubuntu
      wait_for_connection:
        delay: 60
        timeout: 20
      loop: "{{ ec2.instances }}"

- name: Configure instance(s)
  hosts: launched
  become: True
  gather_facts: True
  roles:
    - nginx
